name: Build and Publish Catalog.API

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore Catalog.API/Catalog.API.csproj

    - name: Build
      run: dotnet build Catalog.API/Catalog.API.csproj --no-restore

    - name: Publish
      run: dotnet publish Catalog.API/Catalog.API.csproj -c Release -o ./publish

    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: catalog-api-published
        path: ./publish
