name: Build, Push and Deploy to Azure Container App

on:
  push:
    branches:
      - master

jobs:
  build-push-deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/catalogserviceazuredemo:latest
            ghcr.io/${{ github.repository_owner }}/catalogserviceazuredemo:${{ github.sha }}

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.CATALOGSERVICECONTAINER_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CATALOGSERVICECONTAINER_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CATALOGSERVICECONTAINER_AZURE_SUBSCRIPTION_ID }}

      - name: Deploy to Azure Container Apps
        uses: azure/container-apps-deploy-action@v2
        with:
          registryUrl: ghcr.io
          registryUsername: ${{ github.actor }}
          registryPassword: ${{ secrets.GHCR_PAT }}
          imageToDeploy: ghcr.io/${{ github.repository_owner }}/catalogserviceazuredemo:${{ github.sha }}
          containerAppName: catalogservicecontainer
          resourceGroup: DefaultResourceGroup-CQ
          containerAppEnvironment: managedEnvironment-DefaultResource-b29c
          location: brazilsouth
