name: Deploy existing GHCR image to Azure Container App

on:
  push:
    branches: 
      - master
    paths:
      - '**'
      - '.github/workflows/deploy-to-azure.yaml'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write
      contents: read

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.CATALOGSERVICECONTAINER_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CATALOGSERVICECONTAINER_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CATALOGSERVICECONTAINER_AZURE_SUBSCRIPTION_ID }}

      - name: Deploy to Azure Container Apps
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: .                                # No afecta mucho porque usamos imageToDeploy
          registryUrl: ghcr.io
          registryUsername: ${{ github.actor }}
          registryPassword: ${{ secrets.GHCR_PAT }}
          imageToDeploy: ghcr.io/${{ github.repository_owner }}/catalogserviceazuredemo:latest
          containerAppName: catalogservicecontainer
          resourceGroup: DefaultResourceGroup-CQ
          environment: managedEnvironment-DefaultResource-b29c
          location: brazilsouth
